name: continuous-integration

on: [push, pull_request]

jobs:

  pre-commit:

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
    - uses: pre-commit/action@v2.0.0

  build:

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
    - name: Install python dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: "Build HTML docs"
      run: |
        make -C docs html linkcheck
      env:
        SPHINXOPTS: -nW --keep-going
